name: CI2

env:
  API_KEY: ${{secrets.API_KEY}}
  USERNAME: ${{secrets.USERNAME}}
  ACCESS_KEY: ${{secrets.ACCESS_KEY}}

on:
  push: 
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependencies
      run: |
        cd test-jest
        npm ci
    - name: build the app
      run: |
        cd test-jest
        npm run build
    - name: run component test
      run: |
        cd test-jest
        npm run test
    - name: start the app
      run: |
        cd test-jest
        npm start &
        npx wait-on --timeout 60000

        